default:
  image: 'node:lts'

stages:
  - test
  - build
  - deploy

cache:
  paths:
    - node_modules
    - dist

test-job:
  stage: test
  script:
    - npm install
    - npm run lint

build-job:
  only:
    - master
  stage: build
  script:
    - npm run build
  artifacts:
    name: 'bundle'
    paths:
      - dist/

deploy-job:
  only:
    - master
  stage: deploy
  script:
    - apt update && apt install sshpass -y
    - sshpass -p $PASSWORD ssh $CUSTOM_USERNAME@$CUSTOM_IP "rm -rf /var/www/html/static/sdudoc || echo dir not exists"
    - sshpass -p $PASSWORD scp -o StrictHostKeyChecking=no -r ./dist $CUSTOM_USERNAME@$CUSTOM_IP:/var/www/html/static/sdudoc
